export let products = [
  {
    id: 1,
    title: 'Remera Mercedes',
    price: 15000,
    stock: 4,
    description: 'Mercedes-Benz AMG TM. Remera 2023',
    category: 'remeras',
    img: 'https://i.imgur.com/NznAuDy.png',
  },
  {
    id: 2,
    title: 'Remera Ferrari',
    price: 14500,
    stock: 5,
    description: 'Ferrari TM. Remera 2023',
    category: 'remeras',
    img: 'https://i.imgur.com/VaTq3PE.png',
  },
  {
    id: 3,
    title: 'Remera RedBull',
    price: 19000,
    stock: 2,
    description: 'RedBull TM. Remera 2023',
    category: 'remeras',
    img: 'https://i.imgur.com/Zf9U2iJ.png',
  },
  {
    id: 4,
    title: 'Remera Alpine',
    price: 17800,
    stock: 5,
    description: 'Alpine TM. Remera 2023',
    category: 'remeras',
    img: 'https://i.imgur.com/NUsaSp7.png',
  },
  {
    id: 5,
    title: 'Campera Mercedes',
    price: 15000,
    stock: 4,
    description: 'Mercedes-Benz AMG TM. Campera 2023',
    category: 'camperas',
    img: 'https://i.imgur.com/8G1Xk1I.png',
  },
  {
    id: 6,
    title: 'Campera Ferrari',
    price: 14500,
    stock: 5,
    description: 'Ferrari TM. Campera 2023',
    category: 'camperas',
    img: 'https://i.imgur.com/UOjTheb.png',
  },
  {
    id: 7,
    title: 'Campera RedBull',
    price: 19000,
    stock: 2,
    description: 'RedBull TM. Campera 2023',
    category: 'camperas',
    img: 'https://i.imgur.com/COKhFF8.png',
  },
  {
    id: 8,
    title: 'Campera Alpine',
    price: 17800,
    stock: 5,
    description: 'Alpine TM. Campera 2023',
    category: 'camperas',
    img: 'https://i.imgur.com/IHUWkkn.png',
  },
]
